[package]
name = "dece"
version = "0.1.0"
edition = "2021"

[dependencies]
parse = { path = "../parse"}
cab = "0.6.0"
clap = { version = "4.5.0", features = ["derive"] }
anyhow = "1.0.86"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"