/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "msg.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: zunecom_CommandResp, zunecom_CommandResp_RespLsdir */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: zunecom_CommandResp, zunecom_CommandResp_RespLsdir
#endif
PB_BIND(zunecom_CommandReq, zunecom_CommandReq, 2)


PB_BIND(zunecom_CommandReq_PayloadLsdir, zunecom_CommandReq_PayloadLsdir, 2)


PB_BIND(zunecom_CommandReq_PayloadRdfile, zunecom_CommandReq_PayloadRdfile, 2)


PB_BIND(zunecom_CommandReq_PayloadKwrite32, zunecom_CommandReq_PayloadKwrite32, AUTO)


PB_BIND(zunecom_CommandReq_PayloadKread32, zunecom_CommandReq_PayloadKread32, AUTO)


PB_BIND(zunecom_CommandResp, zunecom_CommandResp, 4)


PB_BIND(zunecom_CommandResp_RespErr, zunecom_CommandResp_RespErr, AUTO)


PB_BIND(zunecom_CommandResp_RespLsdir, zunecom_CommandResp_RespLsdir, 4)


PB_BIND(zunecom_CommandResp_RespLsdir_ent, zunecom_CommandResp_RespLsdir_ent, 2)


PB_BIND(zunecom_CommandResp_RespRdfile, zunecom_CommandResp_RespRdfile, 2)


PB_BIND(zunecom_CommandResp_RespEof, zunecom_CommandResp_RespEof, AUTO)


PB_BIND(zunecom_CommandResp_RespKwrite32, zunecom_CommandResp_RespKwrite32, AUTO)


PB_BIND(zunecom_CommandResp_RespKread32, zunecom_CommandResp_RespKread32, AUTO)







